export const constants = {
  title: "Take Note",
  subtitle: "Capture everything you want to keep handy.",
  google: "google",
  twitter: "twitter",
  github: "github",
  createNote: "Create note",
  noteList: "Notes list",
  noNotesFound: "No notes found",
  writeNote: "Write a note",
  takingNote: "Let's start taking notes!",
  edit: "Edit",
  delete: "Delete",
  cancel: "Cancel",
  accept: "Accept",
  save: "Save",
  deleteNote: "Delete Note",
  sureToDelete: "Are you sure you want to delete?",
  createFolder: "Create folder",
  folderNameError: "Must have at least 3 characters or already exists",
  newFolder: "newFolder",
  alertError: "error",
  alertSuccess: "success",
  saveNoteSuccess: "Note saved!",
  userNotesError: "An error occurred, please try again later",
  saveNoteError: "The note was not saved correctly",
  getNotesError: "Could not retrieve notes",
  updateNoteSuccess: "Note updated!",
  updateNoteError: "Could not update the note",
  deleteNoteError: "Could not delete the note",
  searchNoteError: "Could not perform the search",
};
