export const types = {
  authLogin: "AUTH_LOGIN",
  authLogout: "AUTH_LOGOUT",
  createNote: "CREATE_NOTE",
  saveNote: "SAVE_NOTE",
  activateNote: "ACTIVATE_NOTE",
  activateFolder: "ACTIVATE_FOLDER",
  folders: "ALL_FOLDERS",
  notes: "FOLDER_NOTES",
  deleteNote: "DELETE_NOTE",
  cancelNote: "CANCEL_NOTE",
  logoutNote: "LOGOUST_NOTE",
  searchNote: "SEARCH_NOTE",
  showAlert: "SHOW_ALERT",
  hideAlert: "HIDE_ALERT",
  observableNext: "OBSERVABLE_NEXT",
  showLoader: "SHOW_LOADER",
  hideLoader: "HIDE_LOADER",
  showFolderMobile: "SHOW_FOLDER_MOBILE",
  showNotesMobile: "SHOW_NOTES_MOBILE",
  showNoteMobile: "SHOW_NOTE_MOBILE",
  showModalFolder: "SHOW_MODAL_FOLDER",
  addNewFolder: "ADD_NEW_FOLDER",
  saveFiles: "SAVE_FILES",
  resetFiles: "RESET_FILES",
  removeFiles: "REMOVE_FILES",
  removeUploadFiles: "REMOVE_UPLAOD_FILES",
};
